# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('acceleration', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
            ],
        ),
    ]
