# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_moon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='buildings')),
                ('base_cost_metal', models.PositiveIntegerField(default=0)),
                ('base_cost_crystal', models.PositiveIntegerField(default=0)),
                ('base_cost_deuter', models.PositiveIntegerField(default=0)),
                ('base_energy_use', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_location', models.IntegerField(choices=[(0, 'planetary surface'), (1, 'moon surface')], default=0)),
                ('current_level', models.PositiveIntegerField(default=0)),
                ('new_level', models.PositiveIntegerField(blank=True, null=True)),
                ('upgrade_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.Building')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='locations.Planet')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='playerbuilding',
            unique_together=set([('planet', 'building_location', 'building')]),
        ),
    ]
