# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0002_auto_20171115_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='base_cost',
        ),
        migrations.AddField(
            model_name='building',
            name='base_cost_crystal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='base_cost_deuter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='base_cost_metal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='base_energy_use',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
