# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0003_auto_20171115_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerbuilding',
            old_name='acceleration',
            new_name='capacity',
        ),
    ]
