# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0005_auto_20171115_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPlanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='a planet', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='planettype',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='type',
        ),
        migrations.AddField(
            model_name='planet',
            name='sector',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PlanetType',
        ),
        migrations.AddField(
            model_name='playerplanet',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_draft.Planet'),
        ),
    ]
