# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_draft', '0006_auto_20171115_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_draft.Universe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
