# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0008_remove_playerbuilding_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbuilding',
            name='upgrade_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
