# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_draft', '0012_auto_20171116_2144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerbuilding',
            unique_together=set([('player', 'players_planet', 'building')]),
        ),
    ]
