# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0014_auto_20171116_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerResouce',
            new_name='PlayerResource',
        ),
        migrations.RemoveField(
            model_name='playerplanet',
            name='planet',
        ),
        migrations.AddField(
            model_name='playerplanet',
            name='free_sufrace',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerplanet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='playerplanet',
            name='max_temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplanet',
            name='min_temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplanet',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_draft.PlayerProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerplanet',
            name='position',
            field=models.PositiveIntegerField(choices=[(2, 1), (3, 2), (4, 3), (5, 4), (6, 5), (7, 6), (8, 7), (9, 8)], default=5),
        ),
        migrations.AddField(
            model_name='playerplanet',
            name='sector',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerplanet',
            name='surface',
            field=models.PositiveIntegerField(default=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerbuilding',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_draft.PlayerProfile'),
        ),
        migrations.AlterField(
            model_name='playerplanet',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='playerresource',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_draft.PlayerProfile'),
        ),
        migrations.DeleteModel(
            name='Planet',
        ),
    ]
