# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0016_auto_20171116_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerplanet',
            name='sector',
            field=models.PositiveIntegerField(),
        ),
    ]
