# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0018_auto_20171116_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerplanet',
            name='moon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_draft.Moon'),
        ),
    ]
