# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0019_auto_20171116_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerplanet',
            name='moon',
        ),
        migrations.AddField(
            model_name='moon',
            name='planet',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_draft.PlayerPlanet'),
            preserve_default=False,
        ),
    ]
