# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0020_auto_20171116_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbuilding',
            name='building_location',
            field=models.IntegerField(choices=[(0, 'planet'), (1, 'moon')], default=0),
        ),
    ]
