# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0022_auto_20171116_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerbuilding',
            old_name='upgrade_ends',
            new_name='upgrade_ends_at',
        ),
    ]
