# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0023_auto_20171116_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='playerbuilding',
            name='building_location',
            field=models.IntegerField(choices=[(0, 'planetary surface'), (1, 'moon surface')], default=0),
        ),
    ]
