# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0029_remove_playerbuilding_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='player',
            new_name='owner',
        ),
    ]
