# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0030_auto_20171117_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('type', 'location')]),
        ),
    ]
