# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0031_auto_20171117_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='type',
            new_name='resource_type',
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('resource_type', 'location')]),
        ),
    ]
