# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0032_auto_20171117_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='produced_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerbuilding',
            name='building_location',
            field=models.IntegerField(choices=[(0, 'planetary surface'), (1, 'moon surface')], default=1),
        ),
    ]
