# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0034_remove_resource_produced_per_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='acceleration',
            new_name='production_speed',
        ),
        migrations.RenameField(
            model_name='universe',
            old_name='speed',
            new_name='acceleration',
        ),
    ]
