# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0035_auto_20171117_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='produced_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
