# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0036_resource_produced_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='produced_per_hour',
            field=models.PositiveIntegerField(),
        ),
    ]
