# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0038_auto_20171119_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='capacity_exeeded',
        ),
    ]
