# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0040_auto_20171120_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='new_amount',
            new_name='additional_amount',
        ),
        migrations.AlterField(
            model_name='resource',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
