# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0041_auto_20171120_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='additional_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
