# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0042_auto_20171120_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buildings'),
        ),
    ]
