# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0044_auto_20171122_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbuilding',
            name='building_location',
            field=models.IntegerField(choices=[(0, 'planetary surface'), (1, 'moon surface')], default=0),
        ),
    ]
