# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0046_auto_20171122_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerbuilding',
            old_name='level',
            new_name='current_level',
        ),
    ]
