# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0047_auto_20171122_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbuilding',
            name='new_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
