# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0049_auto_20171125_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerbuilding',
            old_name='update_started_at',
            new_name='upgrade_started_at',
        ),
    ]
