# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0050_auto_20171125_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerbuilding',
            name='upgrade_ends_at',
        ),
    ]
