# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0051_remove_playerbuilding_upgrade_ends_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='free_sufrace',
        ),
    ]
