# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0053_auto_20171126_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Universe',
        ),
    ]
