# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_draft', '0054_delete_universe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
    ]
